//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        public Ingredient()
        {
            this.Measurements = new HashSet<Measurement>();
        }
    
        public int ingredient_id { get; set; }
        public string ingredient_name { get; set; }
    
        public virtual ICollection<Measurement> Measurements { get; set; }
    }
}
